### ISSUE TITLE
Not able to create profile with e-mail address which cannot be found on IOC or IODE websites

### ISSUE THREAD

**Issue by pieterprovoost** [IODEOostende/oeissues#1]
### Expected behaviour

If an e-mail address yields no search results on the IOC or IODE websites, it should be possible to use it to create a new OceanExpert profile. 

### Actual behaviour

Profile creation in OceanExpert fails with `A user with email *** already exists. Please Try another one`.

### Steps to reproduce

1. Go to people search at http://ioc-unesco.org/index.php?option=com_oe&task=people&Itemid=30
2. Search for e-mail address mentioned in screenshot, no results
3. Try to create profile on OceanExpert with same e-mail address

### Context

- Operating system: macOS
- Operating system version: -
- Browser: Firefox
- Browser version: -

![image001](https://user-images.githubusercontent.com/490041/28818304-03dbf0e8-76ab-11e7-9946-4fc1c6b70df4.png)

![image002](https://user-images.githubusercontent.com/490041/28818220-c4d607a8-76aa-11e7-84a7-5ae25578a939.png)

**Comment by AdiKakodkar** [comment]
Thanks for pointing this out. This is not a problem with the system but a misunderstanding of the basic concepts the system uses. Let me explain:
 
When we need to add a person to an event the main requirement is:
 
The person’s PROFILE must be visible in the public interface (without you being logged-in) of OceanExpert: A profile means, an active page of the person with at least the basic details such as Name, affiliation/street address, email address, country, gender etc.
 
Hence, we must first confirm if the person’s PROFILE exists in OceanExpert. To do this:
Login into  OceanExpert and search for the person. You will face the following three scenarios:
1.      If you find the persons PROFILE , you can directly proceed to the event page and search/add the person by email there.
2.      If you do not find the person’s PROFILE, you will need to create a PROFILE for the person in OceanExpert first.
3.      If you find the person’s PROFILE, but the record is deactivated/deleted (persons name is highlighted in orange/red), then you need to contact Mithun and get the record activated and then proceed to the event page to add the person to the event.
 
Now, coming back to your example,
 
It is clear that, Virginie does not have a public PROFILE in OceanExpert. So, following the steps above you should first look for her record in the public interface. Assuming you did this,  I see (in the screenshot) that you started creating a new profile using the “Add Expert” option on the dashboard.
 
While filling up the form you encountered that the EMAIL for Virginie already exists in OceanExpert.
 
Let us agree at this point that a PROFILE and an EMAIL are two different things.
 
This simply means that Virginie had a PROFILE in OceanExpert a long time back and was deactivated/deleted. To avoid duplicates, the system checks this and tells you that there is an old account already present in the system and not to cause issues with statistics the email is locked. The idea is that Virginie can return to OceanExpert anytime now or in the future and reset her password and recreate/update her profile and any statistics linked with her account will be preserved. Hence, you see the following.
 

 
So, if you now go to the event page and try searching the Virginie using her email address, it will obviously complain that Virginies PROFILE does not exist in OceanExpert. Which you see below:
 

 
Considering, we are on the same page until here. The solution is to ask Mithun to remove the locked email address: vinvdv7@gmail.com  and create a PROFILE for Virginie in OceanExpert. Once the PROFILE is created and is publically available (without logging-in) in OceanExpert you will be able to add her to the event with no issue.
 
Thanks again for raising this issue, it raises an important point we have been trying to highlight for a long time.  The OceanExpert is a difficult system to design as thousands of users use it in thousands of different ways and such misunderstanding occur. The SG should consider organizing trainings for different groups of users as it is only in IOC that such an important CRM (Customer Relationship Management) system used daily to manage hundreds of profiles/events/institutions does not have a specific training plan for the users.
