### ISSUE TITLE
Error 404: Page not found.

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#13]
### Expected behaviour
After a certain time of inactivity, the user should be logged out.

### Actual behaviour
After 10 minutes to 2 hours of editing, the system does a logout as if the user has been inactive.
When saving modifications, sometimes an error “404 Page not found” appears and the user is logged out.

Comment (Mithun): Pending.

Since 7 august the error message changed but still pops up like the previous one.

See screenshot:
![screen shot 2017-08-09 at 10 23 30](https://user-images.githubusercontent.com/30799556/29172933-e389f4f0-7de1-11e7-8202-6c6dc666901c.png)

### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by AdiKakodkar** [comment]
This needs some explanation from mithun about the actual behaviour.

**Comment by MarkVanCrombrugge** [comment]
Solved by Mithun.
