### ISSUE TITLE
After a random period, the user is logged out.

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#14]
### Actual behaviour
After 10 minutes to 2 hours of editing, the system does a logout as if the user has been inactive.
When saving modifications, sometines an error “404 Page not found” appears and the user is logged out.

![error404](https://user-images.githubusercontent.com/30799556/29028380-666beaf0-7b84-11e7-91d9-ec3a7b808d00.jpg)

Comment (Mithun): Pending. 
### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by AdiKakodkar** [comment]
Cannot replicate. May be an issue with blocking cookies.
