### ISSUE TITLE
Name search for expert has strange results.

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#15]
### Actual behaviour
A name search for an expert only searches in the first- and last name fields, not in the middle name field.
For user Idalmis(fn) Almeida(mn) Martinez(fn), searching for Almeida does not give any results, search for Idalmis or Martinez finds the person.
This person prefers using the name Almeida instead of Idalmis, which is the case with many Spanish/Portuguese speaking people. (family name of father followed by family name of mother).

Comment (Mithun): Pending.
### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by AdiKakodkar** [comment]
this is now fixed
