### ISSUE TITLE
Console screen: sticky text balloons.

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#18]
### Actual behaviour
In the console screen, the text balloons sometimes stay open after hovering over or clicking on a thumb’s up/down or delete button.

![screen shot 2017-05-15 at 14 51 11](https://user-images.githubusercontent.com/30799556/29028948-3a41c36c-7b86-11e7-85b5-d4df1507d656.png)

![screen shot 2017-05-29 at 09 02 10](https://user-images.githubusercontent.com/30799556/29028986-5d5e7458-7b86-11e7-9993-6a1913b6dd3b.png)

Comment (Mithun): Pending 

### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by AdiKakodkar** [comment]
There is a difference between the two. First one: Yellow background is a label, which gives more info to the user of tooltip
The second is an action box which requires user action. It is opened only after clicking on the delete button above and not by mouse over. Hence it cannot close without clicking a response from the user. This standard behaviour and this can be compared to a dialogue box in the older systemss
