### ISSUE TITLE
Two entries for East Timor

### ISSUE THREAD

**Issue by pieterprovoost** [IODEOostende/oeissues#2]
### Expected behaviour

Single country entry for East Timor and Timor Leste in https://www.iode.org/index.php?option=com_oe&task=countryReports&Itemid=100005

### Actual behaviour

Two entries; each has experts and there are a few participants linked to events and/or training courses. In a "all countries"/"all years" search the course participants are not retrieved.

**Comment by AdiKakodkar** [comment]
this is fixed East Timor is removed as per request from claudia
