### ISSUE TITLE
"Your profile has been successfully created", but it already was.

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#22]
### Actual behaviour
Sometimes (1 in 100 edits), after editing an expert the following screen appears, even when the concerning expert was already active.
The profile existed, was active and was just edited (different street, phone, logo, ...)

![screen shot 2017-07-05 at 10 53 27](https://user-images.githubusercontent.com/30799556/29029702-e0faf366-7b88-11e7-9e4e-12d652f85e7f.png)

Comment (Mithun): Pending
### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by AdiKakodkar** [comment]
Please provide example id's and screenshots. Not possible to replicate.
