### ISSUE TITLE
Creating an "empty" expert.

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#23]
### Actual behaviour
In OE it is possible to create a new expert without mentioning a name.
See picture below, above Gaston Fulquet.

![screen shot 2017-07-07 at 14 03 35](https://user-images.githubusercontent.com/30799556/29029967-c50f6230-7b89-11e7-92fc-a0100a170158.png)

Created a new expert “Barbara8400”.
In personal information, only gender and nationality needed to be specified.
In professional information, only job type(s) needed to be indicated.
All other fields were empty or contained a space.

![screen shot 2017-07-12 at 09 32 00](https://user-images.githubusercontent.com/30799556/29030032-fd8a8f18-7b89-11e7-9233-f6c5dee6b800.png)

![screen shot 2017-07-12 at 09 55 56](https://user-images.githubusercontent.com/30799556/29030319-e511916a-7b8a-11e7-9708-a2cde8b179d6.png)

![screen shot 2017-07-12 at 09 56 17](https://user-images.githubusercontent.com/30799556/29030366-08fe007c-7b8b-11e7-932e-b7bf7efe0a61.png)

Comment (Mithun): Pending. 
### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by AdiKakodkar** [comment]
This has been fixed
