### ISSUE TITLE
Log off: Allow this website to use space on your disk?

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#26]
### Actual behaviour
When logging out of OE, sometimes the following window is displayed.
Clicking “Don’t Allow” a few times sometimes works, but sometimes not and the user has to close the window of even the browser.

![tiles error](https://user-images.githubusercontent.com/30799556/29030820-9866e46c-7b8c-11e7-8054-03cfa0515d44.png)

### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by AdiKakodkar** [comment]
This issue has been solved
