### ISSUE TITLE
Select institution during registration

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#28]
### Expected behaviour
During registration, the new user should only see the active institutions.

### Actual behaviour
During registration, the institution list shows all institutions, also the deactivated and deleted ones.

### Steps to reproduce
A new user waiting for approval in the console.
We know this institution is inactive but the user still selected it.
![screen shot 2017-08-09 at 10 18 43](https://user-images.githubusercontent.com/30799556/29112287-b7d7df92-7ced-11e7-9b3f-f8cf7cf077b9.png)

After clicking on the institution name in the console, we see the institution and associated expert(s).
Here we see the institution is deactivated.
![screen shot 2017-08-09 at 10 19 06](https://user-images.githubusercontent.com/30799556/29112314-cd5db008-7ced-11e7-9a58-fdf68f09f68f.png)

In edit mode, the same institution now has (inactive) behind the name.
![screen shot 2017-08-09 at 10 21 13](https://user-images.githubusercontent.com/30799556/29112334-dbebd352-7ced-11e7-914c-35d8cb7c37d2.png)

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by AdiKakodkar** [comment]
This is not a bug. On closer testing it revealed that when a new person creates a profile and a new institution. The new institution is inactive. If we do not show users the institution they just added (because it is yet to be activated), they will never be able to complete their profile.
