### ISSUE TITLE
Event Calendar  attendence type not showing properly 

### ISSUE THREAD

**Issue by AdiKakodkar** [IODEOostende/oeissues#34]
### Requested by
Claudia
### Expected behaviour
If "Attendence by application" is chosen then it should show below the event in the event calendar.
### Actual behaviour
"Open Attendence" is being shown
### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by mithungawas** [comment]
Event Attendance type on calendar page has been fixed.
