### ISSUE TITLE
Affiliated experts,  second page doesn't show any

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#39]
### Expected behaviour
First page shows five experts of nine.
Second page should show 4 experts.

### Actual behaviour
Affiliated experts (9), first page shows 1-5, when clicking on "2" for the second page with the 4 others,
the page is empty and shows: displaying "1 - 0"

### Steps to reproduce
![screen shot 2017-08-30 at 17 35 31](https://user-images.githubusercontent.com/30799556/29881236-574b02e4-8daa-11e7-8baf-29f2769cd2d8.png)

![screen shot 2017-08-30 at 17 35 50](https://user-images.githubusercontent.com/30799556/29881253-5e97adf4-8daa-11e7-8f8f-b8151914bf82.png)

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by mithungawas** [comment]
The issue has been fixed.
