### ISSUE TITLE
Problem uploading files on OE

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#40]
### Expected behaviour
Uploading files (MS-Word, PDF) into OE.

### Actual behaviour
I’ve noticed that files added through the new OE become ‘corrupted’, and people cannot read them anymore. In this case, I am always using PDF files. Given the problem with the PDF version, I’ve tried with the word version: the system takes up the file but does not take it up in the event. I’ve also tried using www.iode.org<http://www.iode.org> but the problem persists.
When trying to upload the document a second time, the system says it already exists.
People keep coming back reporting files on the website are not readable.

### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by mithungawas** [comment]
The issue has been fixed.
