### ISSUE TITLE
Clicking on an expert gives a progression bar.

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#41]
### Expected behaviour
Edit the expert.
### Actual behaviour
A progression bar is displayed and nothing happens.

The expert:
![screen shot 2017-09-07 at 14 38 08](https://user-images.githubusercontent.com/30799556/30163766-786f92a6-93da-11e7-9500-dbb0fc436801.png)

The progression bar:
![screen shot 2017-09-07 at 14 41 52](https://user-images.githubusercontent.com/30799556/30163834-bd6ea310-93da-11e7-9d19-adcb3f2bdb87.png)

### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by mithungawas** [comment]
The issue has been fixed.
