### ISSUE TITLE
Strange resume screen

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#42]
### Expected behaviour
Click on expert to see overview of the details.

### Actual behaviour
Click on expert to see overview of the details, but on right half of the screen there is a message "Use the following options to change settings for Risa R..." and a list of options like CHange USername, Change Email, Quality control, Member Status, ...

![screen shot 2017-09-07 at 17 24 35](https://user-images.githubusercontent.com/30799556/30210900-d993e98c-949e-11e7-9630-4ab19af66693.png)

### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by mithungawas** [comment]
The issue has been fixed.
