### ISSUE TITLE
Events Calendar: remove summary from events listing page

### ISSUE THREAD

**Issue by wardappeltans** [IODEOostende/oeissues#44]
### Actual behaviour
The information from the summary box is breaking the event's list. This summary info should not be shown on the calendar front page.

### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by mithungawas** [comment]
Summary info has been removed from the calendar event listing.
