### ISSUE TITLE
error when expanding alumni list

### ISSUE THREAD

**Issue by wardappeltans** [IODEOostende/oeissues#45]
### Actual behaviour

the countries are listed multiple times

http://www.ioc-cd.org/index.php?option=com_oe&task=countryReports&report[type]=3&report[expanded]=1

### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS
- Operating system version:
- Browser: Chrome
- Browser version:

**Comment by mithungawas** [comment]
Issue Fixed.
