### ISSUE TITLE
difference between IODE a IOC-CD alumni list

### ISSUE THREAD

**Issue by wardappeltans** [IODEOostende/oeissues#46]
### Actual behaviour
The "learners" of this OTGA course https://www.iode.org/index.php?option=com_oe&task=viewEventParticipants&eventID=1944, are listed on the IODE alumni list, but not on the IOC-CD alumni.

### Steps to reproduce

1.
2.
3.

### Context

- Operating system: macOS
- Operating system version:
- Browser: Chrome
- Browser version:

**Comment by mithungawas** [comment]
Issue Fixed. 
Learners/Instructor roles have been added in the statistics in IOC-CD website.
