### ISSUE TITLE
www.iode.org: empty screen

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#50]
### Description:
On www.iode.org, left menu "Documents/Publications", "Project Office" produces a window with text "IODE Library" and "Search IODE Library" and that's it.

![screen shot 2017-09-15 at 08 44 17](https://user-images.githubusercontent.com/30799556/30470642-c98568b6-99f5-11e7-820b-3d260ada6284.png)

Lies Groen needs this option to manage the IODE library so maybe talk to her.

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by mithungawas** [comment]
Issue has been fixed.
