### ISSUE TITLE
oceanexpert display request

### ISSUE THREAD

**Issue by MarkVanCrombrugge** [IODEOostende/oeissues#62]
### Actual behaviour
At this moment only logged-in users get to see the dates Accom. Contact tel fields to see for an event. However rather than using these for accommodation info and contact tel we have started using the Accom field for details on the participant. I would therefore suggest thefollowing:

Make dates and Accom field visible to all but change the field description of Accom to “Details” and make this field editable only by admin. So when people are asked to confirm participation (when they get the email) allow them to fill ONLY dates and contact tel.
Can this be implemented as soon as possible?

For example see Participants in http://www.ioc-unesco.org/gecd1 )

### Context

- Operating system: macOS/Windows/Linux/iOS/Android
- Operating system version:
- Browser: Chrome/Safari/Firefox/Edge/Internet Explorer
- Browser version:

**Comment by mithungawas** [comment]
dates/accommodation details now visible only after admin login.
