### ISSUE TITLE
Course participants not ending up in statistics

### ISSUE THREAD

**Issue by pieterprovoost** [IODEOostende/oeissues#8]
Reported by CD.

Participants Vito and Virginia participated in https://www.iode.org/index.php?option=com_oe&task=viewEventParticipants&eventID=1944 but the 2017 statistics do not include Cape Verde or Sao Tome e Principe.

> I believe the problem is due to the fact that when uploading the participants on the 2017 course (https://www.iode.org/index.php?option=com_oe&task=viewEventRecord&eventID=1944) I have made the distinction between venues (Maputo or Quelimane), and the system does not read these as Learners. I know there are other examples in the database, and this is due to the lack of a controlled vocabulary.

![screen shot 2017-08-01 at 15 26 58](https://user-images.githubusercontent.com/490041/28830141-36d038c6-76d6-11e7-9e3a-a6dc0bf6a452.png)
![screen shot 2017-08-01 at 15 25 06](https://user-images.githubusercontent.com/490041/28830147-3a8b4604-76d6-11e7-893a-a3885dcb2c25.png)

**Comment by AdiKakodkar** [comment]
This was a data entry problem. System did not support this. We have created a workaround to be able to look for statistics in different scenarios.
